<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title_page}</title>
<!-- ini template parse default top load css and js -->
{css_top}
{js_top}
<!-- end template parse default top load css and js -->
</head>
<body id="{templateName}">
<!-- ini template parse default load data systema -->
<div class="container">

{conteudo}
</div>
<!-- ini template parse default load data systema -->
</body>
<!-- ini template parse default footer load css and js -->
{js_footer}
{css_footer}
<!-- end template parse default footer load css and js -->
</html>
